[build]
  command = "npm run build"
  publish = "dist"

# Disable secrets scanning for public keys and simple password
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Alternative: Only omit specific keys from scanning
# [build.environment]
#   SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_APP_PASSWORD"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
